language: node_js
node_js:
  - "5.10.0"
before_script:
- "npm install -g codeclimate-test-reporter"
script: "gulp cover"
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "codeclimate < ./coverage/lcov.info"
