language: node_js
node_js:
  - "5.10.0"
script: "gulp travis"
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "npm install codeclimate-test-reporter"
  - "codeclimate-test-reporter < coverage/lcov.info"
